import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Layout } from "@/components/Layouts/Layout";
import Navbar from '@/components/Nav';
import { useTheme as useNextTheme } from 'next-themes'
import { Switch, useTheme } from '@nextui-org/react'
import { Banner } from '@/components/Banner';
import { Form } from '@/components/Form';
import { Box } from '@/components/Layouts/Box';

export default function Home() {
  const { setTheme } = useNextTheme();
  const { isDark, type } = useTheme();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <Layout>
          </Layout>
      </main>
    </>
  )
}

/*<div>
            The current theme is: {type}
            <Switch
              checked={isDark}
              onChange={(e) => setTheme(e.target.checked ? 'dark' : 'light')}
            />
          </div>*/
